### ISSUE TITLE
Error during initialization.

### ISSUE THREAD

**Issue by BrunoBonacci** [TheNewNormal/kube-solo-osx#49] opened 2016-04-13 13:33 UTC
Running Kube-Solo v0.5.6 on OSX 10.11.2 

During the initial setup i get the following error

```
Error: rename /tmp/coreos670171957/coreos_production_pxe.vmlinuz /Users/bruno/.coreos/images/stable/899.15.0/coreos_production_pxe.vmlinuz: cross-device link
```

Here the complete output

```
$ /Applications/Kube-Solo.app/Contents/Resources/first-init.command; exit;

Setting up Kubernetes Solo Cluster on OS X

Reading ssh key from /Users/bruno/.ssh/id_rsa.pub

/Users/bruno/.ssh/id_rsa.pub found, updating configuration files ...

Your Mac user's password will be saved in to 'Keychain'
and later one used for 'sudo' command to start VM !!!

This is not the password to access VM via ssh or console !!!

Please type your Mac user's password followed by [ENTER]:
The sudo password is fine !!!


Set CoreOS Release Channel:
 1)  Alpha (may not always function properly)
 2)  Beta
 3)  Stable (recommended)

Select an option: 3


Please type VM's RAM size in GBs followed by [ENTER]:
[default is 2]: 4
Changing VM's RAM to 4GB...


Please type Data disk size in GBs followed by [ENTER]:
[default is 15]: 30

Creating 30GB disk (it could take a while for big disks)...
  30GiB 0:00:31 [ 972MiB/s] [============================================================================================================================================================>] 100%
Created 30GB Data disk

Starting VM ...
> booting k8solo-01
[corectl] downloading and verifying stable/899.15.0
30.07 MB / 30.07 MB [============================================================================================================================================================================] 100.00 %
[corectl] SHA512 hash for coreos_production_pxe.vmlinuz OK
192.65 MB / 192.65 MB [==========================================================================================================================================================================] 100.00 %
[corectl] SHA512 hash for coreos_production_pxe_image.cpio.gz OK
Error: rename /tmp/coreos670171957/coreos_production_pxe.vmlinuz /Users/bruno/.coreos/images/stable/899.15.0/coreos_production_pxe.vmlinuz: cross-device link

Usage:
  corectl load path/to/yourProfile [flags]

Examples:
  corectl load profiles/demo.toml

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"


VM have not booted, please check '~/kube-solo/logs/vm_up.log' and report the problem !!!

Press [Enter] key to continue...
```

I assume that the corectl rather than moving the file after the validation it tries to link it (such as: ln)
and this causes problem when the temp directory is in a different mount point than the kube-solo.

can anyone help me with this?

**Comment by rimusz** [comment] 2016-04-13 18:49
it looks like the coreos image by `corectl` tool was not properly downloaded, try to delete the iso image in `~/.coreos` folder, delete the VM's `~/kube-solo`folder and run `Up`

**Comment by BrunoBonacci** [comment] 2016-04-13 21:28
Hi @rimusz,
as you can see from the output the image verification is successful, so it can't be a broken download (i've tried several times and deleted both `.coreos` and `kube-solo` directories).

I think that the error message is the best clue:

```
Error: rename /tmp/coreos670171957/coreos_production_pxe.vmlinuz /Users/bruno/.coreos/images/stable/899.15.0/coreos_production_pxe.vmlinuz: cross-device link
```

I assume that the underlying implementation of corectl is trying to do the following things:
- download the image in the `/tmp` directory
- verify the integrity with the signature
- move the file in the appropriate location under `.coreos`

now the step i think it is failing is the last one.
it uses the `rename` function (equivalent to `ln` shell tool),
which it can only create a hard link if the target is in the same volume as the source.
see documentation here:

https://developer.apple.com/library/ios/documentation/System/Conceptual/ManPages_iPhoneOS/man2/rename.2.html

Quoting from the doc:

> ```
> [EXDEV]            The link named by new and the file named by old are on
>                    different logical devices (file systems).  Note that
>                    this error code will not be returned if the implemen-
>                    tation permits cross-device links.
> ```

In my case the destination directory in a different volume that my `/tmp`.

The corectl should probably copy and then unlink (similar to `mv`) or allow to customize where the `/tmp` is locate for example under `~/kube-solo/tmp`.

**Comment by rimusz** [comment] 2016-04-13 22:01
@BrunoBonacci can you report that issue on https://github.com/TheNewNormal/corectl please, as the problem is related with `corectl` tool, thanks

**Comment by rimusz** [comment] 2016-05-12 13:21
this problem should be fixed with `corectl` v0.5.5 which is now included in `kube-solo` v0.5.9 release

**Comment by BrunoBonacci** [comment] 2016-05-12 14:07
Hi,
I've just tried with kube-solo 0.5.9 and the problem is still there.
Moreover the related ticket for corectl seems still open.

**Comment by rimusz** [comment] 2016-05-12 14:10
@AntonioMeireles ping

**Comment by AntonioMeireles** [comment] 2016-05-12 14:15
@rimusz commenting on https://github.com/TheNewNormal/corectl/issues/71

**Comment by AntonioMeireles** [comment] 2016-05-13 11:00
fixed in https://github.com/TheNewNormal/corectl/releases/tag/v0.5.6

**Closed as completed by AntonioMeireles** 2016-05-13 11:00 UTC

**Comment by BrunoBonacci** [comment] 2016-05-13 18:19
@rimusz do you have an ETA for a new release?

**Comment by rimusz** [comment] 2016-05-13 18:53
@BrunoBonacci released https://github.com/TheNewNormal/kube-solo-osx/releases/tag/v0.6.0

**Comment by BrunoBonacci** [comment] 2016-05-13 20:42
Thanks for the release. Now it works, but I'm hitting another problem

```
[corectl] stable/899.17.0 ready
Error: unable to validate /etc/exports ('[]')

Usage:
  corectl load path/to/yourProfile [flags]

Examples:
  corectl load profiles/demo.toml

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"


VM have not booted, please check '~/kube-solo/logs/vm_up.log' and report the problem !!!
```

Which seems been already reported https://github.com/TheNewNormal/kube-solo-osx/issues/30

**Comment by AntonioMeireles** [comment] 2016-05-14 12:30
@BrunoBonacci can you plz paste here you existing `/etc/exports` ? thanks!

**Comment by BrunoBonacci** [comment] 2016-05-14 12:59
@AntonioMeireles my `/etc/exports` it's empty.

**Comment by AntonioMeireles** [comment] 2016-05-14 14:19
humm. just remove the file plz and try again.

**Comment by BrunoBonacci** [comment] 2016-05-14 14:39
done that, the error is the same and it creates a new empty `/etc/exports`

**Comment by AntonioMeireles** [comment] 2016-05-14 14:58
`df -k` output please. (sorry lag - on the road this weekend)

**Comment by BrunoBonacci** [comment] 2016-05-14 15:04
```
$ df -k
Filesystem    1024-blocks      Used Available Capacity   iused    ifree %iused  Mounted on
/dev/disk1      390262400  70713236 319293164    19%  17742307 79823291   18%   /
devfs                 184       184         0   100%       638        0  100%   /dev
map -hosts              0         0         0   100%         0        0  100%   /net
map auto_home           0         0         0   100%         0        0  100%   /home
/dev/disk0s4    585509380 461681020 123828360    79% 115420253 30957090   79%   /Volumes/Data
```

**Comment by AntonioMeireles** [comment] 2016-05-14 15:06
ah! your homedir is under /home which is itself a mountpoint so it looks that nfsd is failing to export the homedir. will do some research and come back to you early monday.

**Comment by BrunoBonacci** [comment] 2016-05-14 15:09
Yeah, that was the same cause of the original issue in first place.
Sorry I probably should have made clearer from the beginning.

**Comment by BrunoBonacci** [comment] 2016-06-04 17:30
Hi @AntonioMeireles,
any progress on this?

**Comment by AntonioMeireles** [comment] 2016-06-04 17:34
yes, sorta... _soon_ one will be able to define the mountpoint locations _a la carte_ which workarounds this in some way... after that we plan to stop relying in NFS which will end this issue once and for all.

**Comment by BrunoBonacci** [comment] 2016-06-04 17:53
Great, looking forward to it. thx
