### ISSUE TITLE
New install - 0.6.6 (tried previous versions too) - fleet units not starting up properly. Hangs at waiting...

### ISSUE THREAD

**Issue by dmcnaught** [TheNewNormal/kube-solo-osx#79] opened 2016-06-14 17:41 UTC
``` bash
Identity added: /Users/duncan.mcnaught/.ssh/id_rsa (/Users/duncan.mcnaught/.ssh/id_rsa)
--- ~ » /Users/duncan.mcnaught/Desktop/Kube-Solo.app/Contents/Resources/first-init.command; exit;

Setting up Kubernetes Solo Cluster on OS X

Reading ssh key from /Users/duncan.mcnaught/.ssh/id_rsa.pub

/Users/duncan.mcnaught/.ssh/id_rsa.pub found, updating configuration files ...

Your Mac user's password will be saved in to 'Keychain'
and later one used for 'sudo' command to start VM !!!

This is not the password to access VM via ssh or console !!!

Please type your Mac user's password followed by [ENTER]:
The sudo password is fine !!!


Set CoreOS Release Channel:
 1)  Alpha (may not always function properly)
 2)  Beta
 3)  Stable (recommended)

Select an option: 3


Please type VM's RAM size in GBs followed by [ENTER]:
[default is 2]:
Changing VM's RAM to 2GB...


Please type Data disk size in GBs followed by [ENTER]:
[default is 15]:

Creating 15GB disk ...
  15GiB 0:00:13 [1.12GiB/s] [==================================================================================================>] 100%
Created 15GB Data disk

Starting VM ...
> booting k8solo-01
[corectl] stable/1010.5.0 already available on your system
[corectl] NFS started in order for '/Users/duncan.mcnaught' to be made available to the VMs
[corectl] started 'k8solo-01' in background with IP 192.168.64.2 and PID 3739

Installing Kubernetes files on to VM...
[corectl] uploading 'kube.tgz' to 'k8solo-01:/home/core/kube.tgz'
58.55 MB / 58.55 MB [==================================================================================================================] 100.00 %
Done with k8solo-01


fleetctl is up to date ...

Downloading latest version of helmc for OS X

Installed latest helmc helmc/0.8.1%2Be4b3983 to ~/kube-solo/bin ...
---> Checking repository charts
Updated 1 charts
jenkins
---> Checking repository kube-charts
Already up-to-date.
---> Checking repository deis
Updated 1 charts
workflow-dev
---> Done
[ERROR] Remote kube-charts already exists, and is pointed to https://github.com/TheNewNormal/kube-charts
---> Checking repository charts
Already up-to-date.
---> Checking repository kube-charts
Already up-to-date.
---> Checking repository deis
Already up-to-date.
---> Done

fleetctl list-machines:
MACHINE     IP      METADATA
a16e7089... 192.168.64.2    -

Starting all fleet units in ~/kube-solo/fleet:
Unit fleet-ui.service inactive
Unit fleet-ui.service launched on a16e7089.../192.168.64.2
Unit kube-apiserver.service inactive
Unit kube-apiserver.service launched on a16e7089.../192.168.64.2
Unit kube-controller-manager.service inactive
Unit kube-controller-manager.service launched on a16e7089.../192.168.64.2
Unit kube-scheduler.service inactive
Unit kube-scheduler.service launched on a16e7089.../192.168.64.2
Unit kube-kubelet.service inactive
Unit kube-kubelet.service launched on a16e7089.../192.168.64.2
Unit kube-proxy.service inactive
Unit kube-proxy.service launched on a16e7089.../192.168.64.2

fleetctl list-units:
UNIT                MACHINE             ACTIVE      SUB
fleet-ui.service        a16e7089.../192.168.64.2    activating  start-pre
kube-apiserver.service      a16e7089.../192.168.64.2    inactive    dead
kube-controller-manager.service a16e7089.../192.168.64.2    inactive    dead
kube-kubelet.service        a16e7089.../192.168.64.2    activating  start-pre
kube-proxy.service      a16e7089.../192.168.64.2    activating  start-pre
kube-scheduler.service      a16e7089.../192.168.64.2    inactive    dead

Generate kubeconfig file ...
cluster "k8solo-01" set.
context "default-context" set.
switched to context "default-context".
Waiting for Kubernetes cluster to be ready. This can take a few minutes...
```

When I ssh to VM:

``` bash
CoreOS stable (1010.5.0)
Update Strategy: No Reboots
Failed Units: 2
  kube-certs.service
  update-engine-stub.service
core@k8solo-01 ~ $
```

`````` bash
core@k8solo-01 ~ $ fleetctl list-units
UNIT                MACHINE             ACTIVE      SUB
fleet-ui.service        a16e7089.../192.168.64.2    activating  auto-restart
kube-apiserver.service      a16e7089.../192.168.64.2    inactive    dead
kube-controller-manager.service a16e7089.../192.168.64.2    inactive    dead
kube-kubelet.service        a16e7089.../192.168.64.2    activating  start-pre
kube-proxy.service      a16e7089.../192.168.64.2    activating  start-pre
kube-scheduler.service      a16e7089.../192.168.64.2    inactive    dead```
``````

**Comment by rimusz** [comment] 2016-06-14 17:43
@dmcnaught ssh to VM and check that the Internet is reachable from there

**Comment by dmcnaught** [comment] 2016-06-14 17:46
Doesn't seem like it is @rimusz 

``` bash
curl http://google.com
curl: (6) Couldn't resolve host 'google.com'
```

**Comment by rimusz** [comment] 2016-06-14 17:48
so you need to check what's wrong with you Mac networking then, try just simple reboot first

**Comment by dmcnaught** [comment] 2016-06-14 17:49
I rebooted a few times as part of troubleshooting. I have had no other issues with networking, virtualbox...

**Comment by rimusz** [comment] 2016-06-14 17:50
so something is still not right there, as the App uses `xhyve` based setup and network there is just a bridge.

**Comment by dmcnaught** [comment] 2016-06-14 17:52
Should xhyve be available on my system from the command line?

**Comment by rimusz** [comment] 2016-06-14 17:54
no, it comes with the App as `corectl` tool, which is a wrapper around `xhyve` and made to control CoreOS VMs on Mac.

**Comment by dmcnaught** [comment] 2016-06-14 17:55
How can I view the VM settings?

**Comment by rimusz** [comment] 2016-06-14 17:58
check https://github.com/TheNewNormal/corectl tool and the `user-data` is in `~/kube-solo/cloud-init`

**Comment by AntonioMeireles** [comment] 2016-06-14 18:00
@dmcnaught,  are you by chance behind a firewall ? (trying to isolate root issue)

**Comment by dmcnaught** [comment] 2016-06-14 18:01
@AntonioMeireles No - I'm in my home office.

**Comment by AntonioMeireles** [comment] 2016-06-14 18:05
```
brew install corectl
sudo corectl run
```

gist plz output of `ifconfig`, and `systemctl list-units` of the VM. (and THANKS for your patience) 

(to exit the VM run `sudo halt`)

**Comment by dmcnaught** [comment] 2016-06-14 18:08
`````` bash
sudo corectl run                                                                                                                                  255 ↵
[corectl] alpha/1068.0.0 already available on your system
                                                         [corectl] '/Users/duncan.mcnaught' was already available to VMs via NFS
                                                                                                                                kexec: failed to load kernel /Users/duncan.mcnaught/.coreos/images/alpha/1068.0.0/coreos_production_pxe.vmlinuz
                                                                               Error: signal: abort trap```
``````

**Comment by dmcnaught** [comment] 2016-06-14 18:10
(after I removed /etc/exports)

**Comment by AntonioMeireles** [comment] 2016-06-14 18:10
@dmcnaught what Mac (model) are you running this ?

**Comment by dmcnaught** [comment] 2016-06-14 18:10
MacBookMacBook Pro (Retina, 15-inch, Mid 2015)
2.2 GHz Intel Core i7
16 GB 1600 MHz DDR3
running El Capitan v10.11.5

**Comment by AntonioMeireles** [comment] 2016-06-14 18:12
_interesting_ as that definitivelly supports Vt-x/EPT. `dmesg` output plz.

**Comment by dmcnaught** [comment] 2016-06-14 18:14
Could it be a problem with zsh?

**Comment by AntonioMeireles** [comment] 2016-06-14 18:15
doubt it as also use it :-)

**Comment by dmcnaught** [comment] 2016-06-14 18:16
https://gist.github.com/dmcnaught/99d6d647a2ed4917698ee015544023be

**Comment by dmcnaught** [comment] 2016-06-14 18:32
It's a weird progression:

``` bash
sudo corectl run
[corectl] downloading and verifying alpha/1068.0.0
Error: Signature check for DIGESTS failed.
```

`````` bash
sudo corectl run                                                                                                                                           255 ↵
[corectl] alpha/1068.0.0 already available on your system
Error: unable to validate /etc/exports ('[]')```
``````

**Comment by AntonioMeireles** [comment] 2016-06-14 18:34
better. for the 1st error  `coreos pull -f` would do the trick. 
for the second ... paste your `/etc/exports` plz

**Comment by dmcnaught** [comment] 2016-06-14 18:34
No image in the alpha dir that was created before the error.

**Comment by dmcnaught** [comment] 2016-06-14 18:34
cat /etc/exports  
/Users/duncan.mcnaught -network 192.168.64.0 -mask 255.255.255.0 -alldirs -maproot=root:wheel

**Comment by dmcnaught** [comment] 2016-06-14 18:35
corectl pull -f                                                                                                                              255 ↵
[corectl] downloading and verifying alpha/1068.0.0
Error: Signature check for DIGESTS failed.

**Comment by AntonioMeireles** [comment] 2016-06-14 18:35
strange. lack of image shouldn 't give us trap errors. will try to reproduce.

**Comment by dmcnaught** [comment] 2016-06-14 18:36
``` bash
--- .coreos/images » tree
.
├── alpha
│   └── 1068.0.0
├── beta
└── stable
    └── 1010.5.0
        ├── coreos_production_pxe.vmlinuz
        └── coreos_production_pxe_image.cpio.gz

5 directories, 2 files
```

**Comment by AntonioMeireles** [comment] 2016-06-14 18:37
`corectl version` gives you what ? you are running `0.5.10` right ?

**Comment by dmcnaught** [comment] 2016-06-14 18:37
``` bash
--- .coreos/images » corectl version
CoreOS over OSX made simple.
 - http://github.com/TheNewNormal/corectl
   Copyright (c) 2015-2016, António Meireles

Running version: 0.5.4
                 built with go1.5.3, 2016-01-28 03:16:27 +0000 PST
Latest upstream: 0.5.10
--- .coreos/images » which corectl
/opt/boxen/homebrew/bin/corectl
```

**Comment by AntonioMeireles** [comment] 2016-06-14 18:39
explained... too old. `brew update && brew upgrade --all` should set you right ... (/me crosses fingers)

**Comment by dmcnaught** [comment] 2016-06-14 18:45
ok - VM running - here is output of the two commands:
https://gist.github.com/dmcnaught/d9bd94144f7cfd100feb96e47fae5c32

**Comment by dmcnaught** [comment] 2016-06-14 18:49
on that host:

``` bash
core@6095f71d-ff90-4cf0-8d37-6ec6706204c1 ~ $ curl http://google.com
curl: (6) Couldn't resolve host 'google.com'
```

**Comment by AntonioMeireles** [comment] 2016-06-14 18:50
about to go afk. what timezone are you in ? will reach you tomorrow to sort this out

**Comment by dmcnaught** [comment] 2016-06-14 18:50
USA:MT, ok - thanks

**Comment by AntonioMeireles** [comment] 2016-06-14 18:51
ok. i'm in GMT-0. ping me on your morning. will be around.

**Comment by dmcnaught** [comment] 2016-06-15 15:21
Ping @AntonioMeireles

**Comment by AntonioMeireles** [comment] 2016-06-15 15:22
@dmcnaught i'm n another live debug session atm .. will ping you here after that one :-)

**Comment by dmcnaught** [comment] 2016-06-15 15:22
ok

**Comment by AntonioMeireles** [comment] 2016-06-15 16:13
@dmcnaught can you ping me in kubernetes' slack please ?

**Comment by dmcnaught** [comment] 2016-06-16 18:32
Worked with @AntonioMeireles in Slack - had to turn off Firewall on Mac (then fleet-ui.service starts ok), and also update /etc/resolv.conf in VM to 8.8.8.8 and restart fleet-units.

**Comment by dmcnaught** [comment] 2016-06-16 18:44
/etc/resolv.conf does keep getting re-written back to nameserver 192.168.64.1 though, so I don't really have a useable environment...

**Comment by AntonioMeireles** [comment] 2016-06-16 18:49
@dmcnaught fwiw the issue isn't VM's `/etc/resolv.conf`being populated with `nameserver 192.168.64.1` (where `192.168.64.1` is the address of vmnet's interface), that's macOS' default behaviour. The particular issue in your specific env is that somehow albeit traffic was getting to the outter world from inside the VM the mac wasn 't fwarding back to the vm the DNS queries it was receiving from it, so name resolutions wasn 't working out of the box breaing everything that depended on it. You ended workarounding it by pointing the the VM to a DNS server other than hosts one.

**Comment by dmcnaught** [comment] 2016-06-16 18:51
Ok, right - and that workaround doesn't really seem to persist while using kube-solo in a single session.

**Comment by rimusz** [comment] 2016-07-04 07:46
Internet check is in place in the lasted App version, the error message will pop up if internet is not accessible.
I'm closing this one, as this issue is not really related to the App

**Closed as completed by rimusz** 2016-07-04 07:46 UTC
