### ISSUE TITLE
First time install - Hangs at "Waiting for Kubernetes cluster to be ready. This can take a few minutes..."

### ISSUE THREAD

**Issue by ghost** [TheNewNormal/kube-solo-osx#21] opened 2016-01-22 17:13 UTC
Hi gang, 

Latest everything. 
OS X 10.11.3

Output during initial setup. Looks like fleetctl is not getting installed:

dcvirts-Mac:~ dcvirt$ sudo /Applications/kube-Solo.app/Contents/Resources/first-init.command

Setting up Kubernetes Solo Cluster on OS X

Reading ssh key from /Users/dcvirt/.ssh/id_rsa.pub

/Users/dcvirt/.ssh/id_rsa.pub found, updating configuration files ...

Your Mac user's password will be saved in to 'Keychain'
and later one used for 'sudo' command to start VM !!!

This is not the password to access VM via ssh or console !!!

Please type your Mac user's password followed by [ENTER]:
The sudo password is fine !!!

Set CoreOS Release Channel:
 1)  Alpha
 2)  Beta
 3)  Stable

Select an option: 3

Please type Data disk size in GBs followed by [ENTER]:
[default is 5]:
## Creating 5GB disk ...

Created 5GB Data disk

Starting VM ...

Error: While parsing config: Near line 10 (last key parsed 'k8solo-01.sshkey'): Key 'k8solo-01.sshkey' has already been defined.

Usage:
  corectl load path/to/yourProfile [flags]

Examples:
  corectl load profiles/demo.toml

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Error: 'k8solo-01' not found, or dead

Usage:
  corectl query [VMids] [flags]

Aliases:
  query, q

Flags:
  -a, --all    display extended information about a running CoreOS instance
  -i, --ip     displays given instance IP address
  -j, --json   outputs in JSON for easy 3rd party integration

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Error: 'k8solo-01' not found, or dead

Usage:
  corectl query [VMids] [flags]

Aliases:
  query, q

Flags:
  -a, --all    display extended information about a running CoreOS instance
  -i, --ip     displays given instance IP address
  -j, --json   outputs in JSON for easy 3rd party integration

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Error: 'k8solo-01' not found, or dead

Usage:
  corectl query [VMids] [flags]

Aliases:
  query, q

Flags:
  -a, --all    display extended information about a running CoreOS instance
  -i, --ip     displays given instance IP address
  -j, --json   outputs in JSON for easy 3rd party integration

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Installing Kubernetes files on to VM...
Error: 'k8solo-01' not found, or dead

Usage:
  corectl put path/to/file VMid:/file/path/on/destination [flags]

Aliases:
  put, copy, cp, scp

Examples:
  // copies 'filePath' into '/destinationPath' inside VMid
  corectl put filePath VMid:/destinationPath

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Error: 'k8solo-01' not found, or dead

Usage:
  corectl ssh VMid ["command1;..."] [flags]

Aliases:
  ssh, attach

Examples:
  corectl ssh VMid                 // logins into VMid
  corectl ssh VMid "some commands" // runs 'some commands' inside VMid and exits

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Error: 'k8solo-01' not found, or dead

Usage:
  corectl ssh VMid ["command1;..."] [flags]

Aliases:
  ssh, attach

Examples:
  corectl ssh VMid                 // logins into VMid
  corectl ssh VMid "some commands" // runs 'some commands' inside VMid and exits

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Done with k8solo-01

Error: 'k8solo-01' not found, or dead

Usage:
  corectl ssh VMid ["command1;..."] [flags]

Aliases:
  ssh, attach

Examples:
  corectl ssh VMid                 // logins into VMid
  corectl ssh VMid "some commands" // runs 'some commands' inside VMid and exits

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Downloading fleetctl v for OS X
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21    0    21    0     0     45      0 --:--:-- --:--:-- --:--:--    45
Downloading latest version of helm for OS X
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 4760k  100 4760k    0     0  2152k      0  0:00:02  0:00:02 --:--:-- 4225k

Installed latest helm 0.3.1%2Bd4c0fa8 to ~/kube-solo/bin ...
---> Checking repository charts
---> Cloning into '/Users/dcvirt/.helm/cache/charts'...
Already up-to-date.
---> Done
---> Cloning into '/Users/dcvirt/.helm/cache/kube-charts'...
---> Hooray! Successfully added the repo.
---> Checking repository charts
Already up-to-date.
---> Checking repository kube-charts
Already up-to-date.
---> Done

fleetctl list-machines:
/Applications/kube-Solo.app/Contents/Resources/first-init.command: line 82: fleetctl: command not found

Starting all fleet units in ~/kube-solo/fleet:
/Applications/kube-Solo.app/Contents/Resources/functions.sh: line 288: fleetctl: command not found
/Applications/kube-Solo.app/Contents/Resources/functions.sh: line 289: fleetctl: command not found
/Applications/kube-Solo.app/Contents/Resources/functions.sh: line 290: fleetctl: command not found
/Applications/kube-Solo.app/Contents/Resources/functions.sh: line 291: fleetctl: command not found
/Applications/kube-Solo.app/Contents/Resources/functions.sh: line 292: fleetctl: command not found
/Applications/kube-Solo.app/Contents/Resources/functions.sh: line 293: fleetctl: command not found

fleetctl list-units:
/Applications/kube-Solo.app/Contents/Resources/functions.sh: line 296: fleetctl: command not found

Generate kubeconfig file ...
cluster "k8solo-01" set.
context "default-context" set.
switched to context "default-context".
Waiting for Kubernetes cluster to be ready. This can take a few minutes...

**Comment by rimusz** [comment] 2016-01-22 17:45
no, it looks like you are having a problem with settings file and this is why the VM does not boot for you.
Can you post the `~/kube-solo/settings/k8solo-01.toml` content, please. thanks

**Comment by ghost** [comment] 2016-01-22 18:04
Absolutely:

[k8solo-01]
   uuid = "90394897-5956-4F9D-AFC4-E274C45DAB31"
   channel = "stable"
   volume = "data.img"
   cloud_config = "cloud-init/user-data"
   cpus = 2
   memory = "2048"
   local = "true"
   sshkey = 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClRyPOp59k2zrmwKTtOpQrUTBgITDEiGYF/HcRbxKnkApItsSZdVLrVM88gtegmJ8zc2y6MDliOGVDHmxoooGx3u2mIcBlyIt3k1UvpfhFAoZR3Jju1mkqevOP844JqvZSgZvpzHUT+lvXs6u9rpDOJugUnMxFM/xuYDpK/+ccN6xhFVm34Irb/jQv7Obhe5DkLdnM+Lijv8IJzRVLktBs4k//mTj3+LyQ387RUCoJmLEWQpNdgAS8qtvuKnDAe89j8PPEnpOZSeuzcIlZuqSGu8VbUkl4wG3j4ygQc9OrazabWkYq7WVj1CzEZ58wd68oFtF2LZ+XWopf2vL+dXWD dcvirt@dcvirts-Mac.local'
   sshkey = 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClRyPOp59k2zrmwKTtOpQrUTBgITDEiGYF/HcRbxKnkApItsSZdVLrVM88gtegmJ8zc2y6MDliOGVDHmxoooGx3u2mIcBlyIt3k1UvpfhFAoZR3Jju1mkqevOP844JqvZSgZvpzHUT+lvXs6u9rpDOJugUnMxFM/xuYDpK/+ccN6xhFVm34Irb/jQv7Obhe5DkLdnM+Lijv8IJzRVLktBs4k//mTj3+LyQ387RUCoJmLEWQpNdgAS8qtvuKnDAe89j8PPEnpOZSeuzcIlZuqSGu8VbUkl4wG3j4ygQc9OrazabWkYq7WVj1CzEZ58wd68oFtF2LZ+XWopf2vL+dXWD dcvirt@dcvirts-Mac.local'
   sshkey = 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClRyPOp59k2zrmwKTtOpQrUTBgITDEiGYF/HcRbxKnkApItsSZdVLrVM88gtegmJ8zc2y6MDliOGVDHmxoooGx3u2mIcBlyIt3k1UvpfhFAoZR3Jju1mkqevOP844JqvZSgZvpzHUT+lvXs6u9rpDOJugUnMxFM/xuYDpK/+ccN6xhFVm34Irb/jQv7Obhe5DkLdnM+Lijv8IJzRVLktBs4k//mTj3+LyQ387RUCoJmLEWQpNdgAS8qtvuKnDAe89j8PPEnpOZSeuzcIlZuqSGu8VbUkl4wG3j4ygQc9OrazabWkYq7WVj1CzEZ58wd68oFtF2LZ+XWopf2vL+dXWD dcvirt@dcvirts-Mac.local'

**Comment by zeroem** [comment] 2016-01-22 18:09
I'm in the same boat. Using OSX El Capitan, it looks like there's some issue with the downloading as there's no `fleetctl` in the `~/kube-solo/bin` directory.

[Install Log](https://gist.github.com/zeroem/fd66f560081694a34e74)
[settings.toml](https://gist.github.com/zeroem/91158656be6fd28e58dc)

**Comment by rimusz** [comment] 2016-01-22 18:41
@drcamp hmm, in your settings file there should be only one `sshkey =...`, as having more gives the error. Which App version are you using?

**Comment by rimusz** [comment] 2016-01-22 18:43
@zeroem you settings file looks fine, for some reason VM does not boot.
Which App version are you using?

**Comment by ghost** [comment] 2016-01-22 19:37
Using 0.4.6

I started from scratch and get the same problem. The extra ssh entries were due to me retrying the setup after ctl-c and running /Applications/Kube-Solo.app/Contents/Resources/first-init.command.

**Comment by rimusz** [comment] 2016-01-22 20:53
@drcamp can you try new v0.4.7 version, please?

**Comment by ghost** [comment] 2016-01-22 21:29
@rimusz 

Same problem. Run setup as sudo, fleetctl is not getting installed.

**Comment by zeroem** [comment] 2016-01-22 21:30
@rimusz I was installing `0.4.6`

I'll try the newer version and report back.

**Comment by zeroem** [comment] 2016-01-22 21:35
Same boat with `0.4.7`

[Install Log and Settings](https://gist.github.com/zeroem/0fb84b8702498d790068)

**Comment by ghost** [comment] 2016-01-22 21:37
@zeroem 
I can get past that issue if I ctl-c as soon as the script starts and run it via sudo, but get to the "Waiting for Kubernetes cluster...." and it hangs

**Comment by rimusz** [comment] 2016-01-22 21:48
sudo is not needed there if you follow the right install procedure.
@AntonioMeireles can we get your input here?

**Comment by ghost** [comment] 2016-01-22 22:05
UPDATE:

Removed all kube-solo bits, rebooted machine, installed with 0.4.7 and all is well thus far. Not sure what the issue was.

**Comment by rimusz** [comment] 2016-01-22 22:12
cool, can we close this then?

**Comment by ghost** [comment] 2016-01-22 22:19
@rimusz 
Yes, let's do. I will work on it tonight and start a new issue-thread if needed. 

Thanks everyone,
-DC

**Comment by rimusz** [comment] 2016-01-22 22:20
awesome

**Comment by jtblin** [comment] 2016-02-14 03:22
I'm getting the same problem with `0.5.2`. Upgraded an existing installation deleting kube-solo directory as indicated, after reboot I couldn't get `kube-solo` to work anymore. Removed the app `rm -rf /Applications/Kube-Solo.app` and kube-solo directory `rm -rf ~/kube-solo` and tried reinstalling but it's stuck on `Waiting for Kubernetes cluster to be ready. This can take a few minutes...`.

```
Last login: Sun Feb 14 14:04:02 on ttys005
/Applications/Kube-Solo.app/Contents/Resources/first-init.command; exit;
~ $ /Applications/Kube-Solo.app/Contents/Resources/first-init.command; exit;

Setting up Kubernetes Solo Cluster on OS X

Reading ssh key from /Users/jtblin/.ssh/id_rsa.pub

/Users/jtblin/.ssh/id_rsa.pub found, updating configuration files ...

Your Mac user's password will be saved in to 'Keychain'
and later one used for 'sudo' command to start VM !!!

This is not the password to access VM via ssh or console !!!

Please type your Mac user's password followed by [ENTER]:
The sudo password is fine !!!


Set CoreOS Release Channel:
 1)  Alpha
 2)  Beta
 3)  Stable (recommended)

Select an option: 3


Please type VM's RAM size in GBs followed by [ENTER]:
[default is 2]:
Changing VM's RAM to 2GB...


Please type Data disk size in GBs followed by [ENTER]:
[default is 10]:

Creating 10GB disk ...
  10GiB 0:00:15 [ 675MiB/s] [=====================================================================================================================>] 100%
Created 10GB Data disk

Starting VM ...
> booting k8solo-01
[corectl] unable to guess the MAC Address from the provided UUID (90394897-5956-4F9D-AFC4-E274C45DAB31). Using a randomly generated one one
[corectl] stable/835.12.0 already available on your system
[corectl] NFS started in order for '/Users/jtblin' to be made available to the VMs
[corectl] started 'k8solo-01' in background with IP 192.168.64.5 and PID 78398
Error: 'k8solo-01' not found, or dead

Usage:
  corectl query [VMids] [flags]

Aliases:
  query, q

Flags:
  -a, --all    display extended information about a running CoreOS instance
  -i, --ip     displays given instance IP address
  -j, --json   outputs in JSON for easy 3rd party integration

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Error: 'k8solo-01' not found, or dead

Usage:
  corectl query [VMids] [flags]

Aliases:
  query, q

Flags:
  -a, --all    display extended information about a running CoreOS instance
  -i, --ip     displays given instance IP address
  -j, --json   outputs in JSON for easy 3rd party integration

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Error: 'k8solo-01' not found, or dead

Usage:
  corectl query [VMids] [flags]

Aliases:
  query, q

Flags:
  -a, --all    display extended information about a running CoreOS instance
  -i, --ip     displays given instance IP address
  -j, --json   outputs in JSON for easy 3rd party integration

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"


Installing Kubernetes files on to VM...
Error: 'k8solo-01' not found, or dead

Usage:
  corectl put path/to/file VMid:/file/path/on/destination [flags]

Aliases:
  put, copy, cp, scp

Examples:
  // copies 'filePath' into '/destinationPath' inside VMid
  corectl put filePath VMid:/destinationPath

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Error: 'k8solo-01' not found, or dead

Usage:
  corectl ssh VMid ["command1;..."] [flags]

Aliases:
  ssh, attach

Examples:
  corectl ssh VMid                 // logins into VMid
  corectl ssh VMid "some commands" // runs 'some commands' inside VMid and exits

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Error: 'k8solo-01' not found, or dead

Usage:
  corectl ssh VMid ["command1;..."] [flags]

Aliases:
  ssh, attach

Examples:
  corectl ssh VMid                 // logins into VMid
  corectl ssh VMid "some commands" // runs 'some commands' inside VMid and exits

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Done with k8solo-01

Error: 'k8solo-01' not found, or dead

Usage:
  corectl ssh VMid ["command1;..."] [flags]

Aliases:
  ssh, attach

Examples:
  corectl ssh VMid                 // logins into VMid
  corectl ssh VMid "some commands" // runs 'some commands' inside VMid and exits

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"


fleetctl is up to date ...

Downloading latest version of helm for OS X
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 4760k  100 4760k    0     0  1109k      0  0:00:04  0:00:04 --:--:-- 1787k

Installed latest helm 0.3.1%2Bd4c0fa8 to ~/kube-solo/bin ...
---> Checking repository charts
Already up-to-date.
---> Checking repository kube-charts
Already up-to-date.
---> Done
[ERROR] Remote kube-charts already exists, and is pointed to https://github.com/TheNewNormal/kube-charts
---> Checking repository charts
Already up-to-date.
---> Checking repository kube-charts
Already up-to-date.
---> Done

fleetctl list-machines:
2016/02/14 14:07:03 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error retrieving list of active machines: dial tcp :2379: connection refused

Starting all fleet units in ~/kube-solo/fleet:
2016/02/14 14:07:03 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error creating units: error retrieving Unit(fleet-ui.service) from Registry: dial tcp :2379: connection refused
2016/02/14 14:07:03 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error creating units: error retrieving Unit(kube-apiserver.service) from Registry: dial tcp :2379: connection refused
2016/02/14 14:07:03 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error creating units: error retrieving Unit(kube-controller-manager.service) from Registry: dial tcp :2379: connection refused
2016/02/14 14:07:03 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error creating units: error retrieving Unit(kube-scheduler.service) from Registry: dial tcp :2379: connection refused
2016/02/14 14:07:03 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error creating units: error retrieving Unit(kube-kubelet.service) from Registry: dial tcp :2379: connection refused
2016/02/14 14:07:03 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error creating units: error retrieving Unit(kube-proxy.service) from Registry: dial tcp :2379: connection refused

fleetctl list-units:
2016/02/14 14:07:03 ERROR fleetctl.go:216: error attempting to check latest fleet version in Registry: dial tcp :2379: connection refused
Error retrieving list of units from repository: dial tcp :2379: connection refused

Generate kubeconfig file ...
cluster "k8solo-01" set.
context "default-context" set.
switched to context "default-context".
Waiting for Kubernetes cluster to be ready. This can take a few minutes...
```

**Comment by jtblin** [comment] 2016-02-14 03:24
Content of `~/kube-solo/settings/k8solo-01.toml`

```
[k8solo-01]
   uuid = "90394897-5956-4F9D-AFC4-E274C45DAB31"
   channel = "stable"
   volume = "data.img"
   cloud_config = "cloud-init/user-data"
   cpus = 2
   memory = 2048
   local = "true"
   sshkey = 'ssh-rsa redactd jtblin@redacted.com'
```

**Comment by jtblin** [comment] 2016-02-14 03:27
kubeconfig server address seems weird:

```
$ cat ~/kube-solo/kube/kubeconfig 
apiVersion: v1
clusters:
- cluster:
    server: http://:8080
  name: k8solo-01
contexts:
- context:
    cluster: k8solo-01
    user: ""
  name: default-context
current-context: default-context
kind: Config
preferences: {}
users: []
```

**Comment by jtblin** [comment] 2016-02-14 22:24
After I deleted everything again and rebooted my MBP, I selected the `Beta` CoreOS release channel and I was able to install the latest version without issue. 

Either there was something weird going on and it needed a reboot, either kube-solo uses the kubelet installed on CoreOS to boostrap Kubernetes? kubelet is not part of the coreos stable release channel anymore: https://github.com/coreos/bugs/issues/985.

**Comment by rimusz** [comment] 2016-02-16 08:53
@jtblin kube-solo does not use the `kubelet` which comes with coreos.
all files required by kubernetes get copied to VM when install is done

and the `~/kube-solo/kube/kubeconfig` has not server IP because the VM was not able to start

**Comment by esbenp** [comment] 2016-03-08 13:36
I have the same error when trying to boot up my VM. I do not know if the two issues are unrelated, since this occurs on boots after the initial, and I do not get any fleetctl errors.

If i destroy my Kube-Solo VM and recreate it I can get it to work the first time. However, I am unable to get it up and running after I halt my VM.

I get this error with both stable and beta version of CoreOS.

I have a docker-machine VM installed as well, do not know if anything is conflicting there (stopping my docker-machine does not work)

Kube-Solo-OSX version: `0.5.3`
OSX version: `10.11`
Output

```
Last login: Tue Mar  8 14:28:27 on ttys001
Esbens-MacBook-Pro:~ esbenp$ /Applications/Kube-Solo.app/Contents/Resources/up.command; exit;

Starting VM ...
> booting k8solo-01
[corectl] beta/899.9.0 already available on your system
[corectl] '/Users/esbenp' was already available to VMs via NFS
[corectl] started 'k8solo-01' in background with IP 192.168.64.2 and PID 45052

Waiting for VM to be ready...
-
```

Let me know what files to output for debugging

**Comment by rimusz** [comment] 2016-03-08 14:02
@esbenp ssh to kube-solo VM and check that the internet is accessible from there

**Comment by esbenp** [comment] 2016-03-08 15:25
```
Last login: Tue Mar  8 16:13:57 on ttys004
Esbens-MacBook-Pro:~ esbenp$ /Applications/Kube-Solo.app/Contents/Resources/ssh.command; exit;
Last login: Tue Mar  8 13:30:13 2016
CoreOS stable (899.9.0)
Update Strategy: No Reboots
Failed Units: 1
  docker.service
core@k8solo-01 ~ $ curl http://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="http://www.google.dk/?gws_rd=cr&amp;ei=0u7eVqwOqNHoBIXckvgM">here</A>.
</BODY></HTML>
```

**Comment by rimusz** [comment] 2016-03-08 15:49
@esbenp you have failed docker.service unit there, check it's logs
and post it here

**Comment by esbenp** [comment] 2016-03-08 17:40
```
CoreOS stable (899.9.0)
Update Strategy: No Reboots
Failed Units: 1
  docker.service
core@k8solo-01 ~ $ journalctl -u docker.service
-- Logs begin at Tue 2016-03-08 13:30:08 UTC, end at Tue 2016-03-08 17:39:37 UTC. --
Mar 08 13:30:12 k8solo-01 systemd[1]: Dependency failed for Docker Application Container Engine.
Mar 08 13:30:12 k8solo-01 systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Mar 08 13:30:22 k8solo-01 systemd[1]: Started Docker Application Container Engine.
Mar 08 13:30:23 k8solo-01 dockerd[1006]: time="2016-03-08T13:30:23.141345843Z" level=fatal msg="Error starting daemon: lstat /var/lib/d
Mar 08 13:30:23 k8solo-01 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Mar 08 13:30:23 k8solo-01 systemd[1]: docker.service: Unit entered failed state.
Mar 08 13:30:23 k8solo-01 systemd[1]: docker.service: Failed with result 'exit-code'.
lines 1-8/8 (END)
```

**Comment by rimusz** [comment] 2016-03-08 20:59
@esbenp can you `journalctl -u docker.service -l`as the messages are cut

**Comment by esbenp** [comment] 2016-03-09 08:02
```
CoreOS stable (899.9.0)
Update Strategy: No Reboots
Failed Units: 1
  docker.service
core@k8solo-01 ~ $ journalctl -u docker.service -l
-- Logs begin at Tue 2016-03-08 13:30:08 UTC, end at Wed 2016-03-09 08:01:32 UTC. --
Mar 08 13:30:12 k8solo-01 systemd[1]: Dependency failed for Docker Application Container Engine.
Mar 08 13:30:12 k8solo-01 systemd[1]: docker.service: Job docker.service/start failed with result 'dependency'.
Mar 08 13:30:22 k8solo-01 systemd[1]: Started Docker Application Container Engine.
Mar 08 13:30:23 k8solo-01 dockerd[1006]: time="2016-03-08T13:30:23.141345843Z" level=fatal msg="Error starting daemon: lstat /var/lib/docker/volumes/65a7aad8ad1b612babb001d8cbdbe45775697d3ba5a73942e8740810aa70ef68: input/output error"
Mar 08 13:30:23 k8solo-01 systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Mar 08 13:30:23 k8solo-01 systemd[1]: docker.service: Unit entered failed state.
Mar 08 13:30:23 k8solo-01 systemd[1]: docker.service: Failed with result 'exit-code'.
```

I tried `docker volume ls`

```
core@k8solo-01 ~ $ docker volume ls
An error occurred trying to connect: Get http:///var/run/docker.sock/v1.21/volumes: read unix /var/run/docker.sock: connection reset by peer
```

**Comment by rimusz** [comment] 2016-03-09 08:57
this is our problem `lstat /var/lib/docker/volumes/65a7aad8ad1b612babb001d8cbdbe45775697d3ba5a73942e8740810aa70ef68: input/output error`
The docker did not get mounted properly, I use `ext4` there, will try to switch to `btrfs` in the next release.
Heading to the KubeCon today, so will cut a new version next week

@AntonioMeireles any advice on this problem?

**Comment by wstrange** [comment] 2016-03-14 23:33
Not sure if this is related, but I can no longer bring up kube-solo. etcd wont start
Mar 14 23:31:13 k8solo-01 etcd2[1431]: read wal error (walpb: crc mismatch) and
Mar 14 23:31:13 k8solo-01 systemd[1]: etcd2.service: Main process exited, code=e
Mar 14 23:31:13 k8solo-01 systemd[1]: Failed to start etcd2.
Mar 14 23:31:13 k8solo-01 systemd[1]: etcd2.service: Unit entered failed state.
Mar 14 23:31:13 k8solo-01 systemd[1]: etcd2.service: Failed with result 'exit-co

And I get errors related to ext4:

EXT4-fs error (device vda): ext4_mb_generate_buddy:758: group 100, block bitmap and bg descriptor inconsistent: 1484 vs 1558 free clusters
[   18.839329] EXT4-fs error (device vda): ext4_mb_generate_buddy:758: group 17, block bitmap and bg descriptor inconsistent: 890 vs 1363 free clusters
[   18.840453] JBD2: Spotted dirty metadata buffer (dev = vda, blocknr = 0). There's a risk of filesystem corruption in case of system crash.
[   18.841263] EXT4-fs error (device vda): ext4_mb_generate_buddy:758: group 18, block bitmap and bg descriptor inconsistent: 14094 vs 14097 free clusters
[   18.842110] JBD2: Spotted dirty metadata buffer (dev = vda, blocknr = 0). There's a risk of filesystem corruption in case of system crash.
[  308.232207] EXT4-fs (vda): error count since last fsck: 17
[  308.232903] EXT4-fs (vda): initial error at time 1457989316: mb_free_blocks:1454: block 600816
[  308.233672] EXT4-fs (vda): last error at time 1457998088: ext4_mb_generate_buddy:758

**Comment by openjack** [comment] 2016-04-01 16:27
Switching to 'beta' got me passed the "Waiting for Kubernetes cluster to be ready..." issue.

**Comment by chrislovecnm** [comment] 2016-05-10 14:25
@openjack I had to tank the install, and then go to beta.  From there I can start it.  At least start it once 😄

**Comment by rimusz** [comment] 2016-05-13 18:55
guys can you try the latest https://github.com/TheNewNormal/kube-solo-osx/releases/tag/v0.6.0 to see if the problem still exists, thanks

**Comment by chrislovecnm** [comment] 2016-05-14 03:42
Same thing @rimusz ... btw I switched the k8s version during "Waiting for Kubernetes cluster to be ready..." issue, and it fixed it.

**Comment by rimusz** [comment] 2016-05-27 20:17
Latest v0.6.3 addresses those issues

**Comment by VahidR** [comment] 2016-06-15 11:19
I used the version **v0.6.6** and the problem still exits.
The workaround for me, as others said, was to use the "**Beta**" version of CoreOS

**Comment by ayberk** [comment] 2016-06-21 20:35
Can confirm the issue still does exist (macOS 10.11.15) and using "beta" was the fix.

**Comment by vichargrave** [comment] 2016-06-22 22:29
I'm trying to use v0.6.6 on Mac OS 10.11.15, but it is still hanging at the Kubernetes startup cluster step.

**Comment by rimusz** [comment] 2016-06-26 15:02
I will introduce in the next version of the App more checks and more detailed error messages to know what the problem is.

**Comment by clubanderson** [comment] 2016-06-29 20:40
try to restart nfs

sudo nfsd restart

**Comment by chrislovecnm** [comment] 2016-06-29 20:54
@rimusz it would be good to have a check that `nfsd` is functioning correctly.

**Comment by rimusz** [comment] 2016-06-30 14:13
@chrislovecnm already tried to introduce `nfsd restart` and `nfsd update` without a luck :(
we hope with Antonio to have new version of `corectl` soon, which will have optional `nfs` as in most cases it is not needed on kube apps

**Comment by rimusz** [comment] 2016-07-08 20:32
the latest v0.8.0 should fix all these problems

**Closed as completed by rimusz** 2016-07-08 20:32 UTC
