### ISSUE TITLE
Error when trying to install Helm

### ISSUE THREAD

**Issue by jgsqware** [TheNewNormal/kube-solo-osx#143] opened 2016-10-17 15:05 UTC
Hello, I'm trying to install Kube-Solo and it can't install Helm

Here is the logs:

```
Checking for latest Helm version...

Downloading latest v2.0.0-alpha.5 of 'helm' cli for macOS
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    21    0    21    0     0     38      0 --:--:-- --:--:-- --:--:--    37
chmod: helm: No such file or directory
mv: rename helm to /Users/jgsqware/kube-solo/bin/helm: No such file or directory
```

I've tried a fresh install by removing kube-solo folder but not working.

**Comment by rimusz** [comment] 2016-10-17 15:09
sorry, have not updated helm install part yet, as it got changed again in upstream :)

**Comment by rimusz** [comment] 2016-10-18 09:35
fixed in https://github.com/TheNewNormal/kube-solo-osx/releases/tag/v0.9.7

**Comment by jgsqware** [comment] 2016-10-18 10:25
cool thanks

**Comment by olalonde** [comment] 2016-10-29 09:34
After running the up command I got an error related to helm (`/Users/olalonde/kube-solo/bin/helm: No such file or directory`):

```
Last login: Sat Oct 29 02:18:47 on ttys002
/Applications/Kube-Solo.app/Contents/Resources/up.command; exit;
~$ /Applications/Kube-Solo.app/Contents/Resources/up.command; exit;

Starting k8solo-01 VM ...

Data disk does not exist, it will be created now ...

Please type Data disk size in GBs followed by [ENTER]:
[default is 30]:

Creating 30GB sparse disk (QCow2)...
-
Created 30GB Data disk

Starting VM ...

> booting k8solo-01 (1/1)
---> 'k8solo-01' started successfuly with address 192.168.64.3 and PID 7993
---> 'k8solo-01' boot logs can be found at '/Users/olalonde/.coreos/running/90394897-5956-4F9D-AFC4-E274C45DAB31/log'
---> 'k8solo-01' console can be found at '/Users/olalonde/.coreos/running/90394897-5956-4F9D-AFC4-E274C45DAB31/tty'

Checking internet availablity on VM...
Yes, internet is available ...

Installing Kubernetes files on to VM...
2016-10-29 02:22:19.095492 I | uploading 'kube.tgz' to 'k8solo-01:/home/core/kube.tgz'
101.24 MB / 101.24 MB [==============================================] 100.00 %
                                                                                Files copied to VM...
Installing now ...
Done...

Generating kubeconfig file ...
cluster "k8solo-01" set.
context "kube-solo" set.
switched to context "kube-solo".

Waiting for etcd service to be ready on VM...
...

Waiting for Kubernetes cluster to be ready. This can take a bit...
\...

Waiting for Kubernetes node to be ready. This can take a bit...
\...

node "k8solo-01" labeled

Creating kube-system namespace ...

Installing SkyDNS ...
replicationcontroller "kube-dns-v19" created
service "kube-dns" created

Installing Kubernetes Dashboard ...
service "kubernetes-dashboard" created
replicationcontroller "kubernetes-dashboard-v1.4.0" created

Installing Helm Tiller service ...
service "tiller-deploy" created

Installing Helm Tiller...
/Applications/Kube-Solo.app/Contents/Resources/up.command: line 144: /Users/olalonde/kube-solo/bin/helm: No such file or directory

kubectl cluster-info:
Kubernetes master is running at http://192.168.64.3:8080
KubeDNS is running at http://192.168.64.3:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at http://192.168.64.3:8080/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

Cluster version:
Client version: v1.4.4
Server version: v1.4.4

kubectl get nodes:
NAME        STATUS    AGE
k8solo-01   Ready     12s
```

```
$ ls -al ~/kube-solo/bin
total 134248
drwxr-xr-x  10 olalonde  staff       340 Oct 29 02:22 .
drwxr-xr-x  11 olalonde  staff       374 Oct 29 02:22 ..
-rwxr-xr-x   1 olalonde  staff       290 Oct 29 02:22 etcdctl
-rwxr-xr-x   1 olalonde  staff    155312 Oct 29 02:22 gsed
-rwxr-xr-x   1 olalonde  staff      4753 Oct 29 02:22 install_deis
-rwxr-xr-x   1 olalonde  staff    630720 Oct 29 02:22 jq
-rwxr-xr-x   1 olalonde  staff       789 Oct 29 02:22 ksolo
-rwxr-xr-x@  1 olalonde  staff  67235024 Oct 29 02:20 kubectl
-rwxr-xr-x   1 olalonde  staff       286 Oct 29 02:22 rkt
-rwxr-xr-x   1 olalonde  staff    691840 Oct 29 02:22 wget
```

**Comment by rimusz** [comment] 2016-10-30 19:37
@olalonde I can you explain the steps you did there, so I can try to reproduce it, thanks

**Comment by olalonde** [comment] 2016-10-31 02:02
Tried again from scratch and couldn't reproduce!

**Closed as completed** 2016-11-14 10:50 UTC
Labels: bug
